---
title: "Web Scraping: Fastest Lap Data"
format: html
---

```{r}
# Import packages
library(rvest)
library(dplyr)
library(purrr)
library(tidyr)
library(stringr)
library(writexl)
```

```{r}
# Function to retrieve race result URLs
scrape_race_results <- function(urls) {
  
  map_df(urls, function(url) {
    
    page <- read_html(url)
    rows <- page %>% html_elements("table tbody tr")
    
    map_df(rows, function(row) {
      
      race_node <- row %>% html_element("td:first-child a")
      
      tibble(
        race_link = race_node %>% html_attr("href")
      )
    })
  }) %>%
    mutate(full_link = paste0("https://www.formula1.com", race_link)) %>%
    pull(full_link)
}


# Function to retrieve fastest lap URLs
scrape_fastest_laps <- function(urls) {
  
  scrape_race_results(urls) %>%
    str_replace("race-result$", "fastest-laps")
}
```

```{r}
# List of seasonal results pages
f1_season_urls <- paste0(
  "https://www.formula1.com/en/results/",
  1999:2025,
  "/races"
)

fastest_lap_urls <- scrape_fastest_laps(f1_season_urls)
```

```{r}
# Function to retrieve fastest lap result data
scrape_fastest_laps <- function(urls) {
  
  race_name <- urls %>%
    str_split("/") %>%
    unlist() %>%
    .[length(.) - 1] %>%
    str_to_title()
  
  year <- urls %>%
    str_split("/") %>%
    unlist() %>%
    .[6]
  
  page <- read_html(urls)
  
  df <- page %>%
    html_node("table") %>%
    html_table() %>%
    select(`Pos.`, Team) %>%
    mutate(
      `Pos.` = suppressWarnings(as.numeric(`Pos.`))
    ) %>%
    filter(`Pos.` == 1) %>%
    mutate(
      Year = as.integer(year)
    )
  
  return(df)
}
```

```{r}
# Run web scraping function on all fastest lap results (2000-present)
fastest_lap_results <- map_dfr(fastest_lap_urls, scrape_fastest_laps)
```

```{r}
# Group results by year and team
fastest_lap_results <- fastest_lap_results %>%
  group_by(Year, Team) %>%
  summarise(
    fastest_lap_count = sum(Pos., na.rm = TRUE),
    .groups = "drop"
  )
```

```{r}
write.csv(fastest_lap_results, "Data_Files/fastest_laps.csv", row.names = FALSE)
```
